Resolved issue #12
laravel-notification-channels/smsc-ru pull request #18
Opened 2017-12-08 17:00 UTC by webdevium

- changed constructor arguments
- added tests for custom host config
- added documentation for customization host

2017-12-11 18:12 UTC, jhaoda requested changes

2017-12-11 18:12 UTC, jhaoda commented on README.md
> +    'host' => 'http://www1.smsc.kz/',
Надо вынести в `.env`.

2017-12-11 18:12 UTC, jhaoda commented on README.md
> +> If smsc.ru is not responding, you can set custom host WITH trailing slash
Не очень понятно, можно подумать, что пакет автоматом переключится на этот хост, если основной не отвечает.

2017-12-11 18:12 UTC, jhaoda commented on src/SmscRuApi.php
> +    public function __construct($config)
`array $config`

2017-12-11 18:12 UTC, jhaoda commented on src/SmscRuApi.php
> +        $this->url = array_get($config, 'host', 'https://smsc.ru/').'sys/send.php';
`Arr::get`

2018-03-23 11:57 UTC, Barmunksu commented
merge plz!

2018-03-30 02:39 UTC, jhaoda approved these changes

2018-03-30 02:39 UTC, merged